Update init script to get more robustness

diff --git a/openpbs/pbs_init b/openpbs/pbs_init
--- a/openpbs/pbs_init
+++ b/openpbs/pbs_init
@@ -6,16 +6,22 @@ mom_config=/var/spool/pbs/mom_priv/config
 org_script=/opt/pbs/libexec/pbs_init.d
 hostname=$(cat /etc/hostname)
 
+prestart(){
+  # cleanup stale lock files
+  find /var/spool/pbs -name "*.lock" -delete
+  rm -f /var/spool/pbs/datastore/postmaster.pid
+}
+
 depend(){
   need net
 }
 
 start(){
   # rewrite PBS config files to start all server
-  sed -i -e "s/PBS_SERVER=.*/PBS_SERVER=${hostname}/" \
-         -e "s/PBS_START_MOM=0/PBS_START_MOM=1/" /etc/pbs.conf
-  echo PBS_AUTH_METHOD=MUNGE >>/etc/pbs.conf
-  echo PBS_SUPPORTED_AUTH_METHODS="munge" >>/etc/pbs.conf
+  sed -i -e "s/PBS_SERVER=.*/PBS_SERVER=${hostname}/" -e "s/PBS_START_MOM=0/PBS_START_MOM=1/" /etc/pbs.conf
+
+  grep -q "PBS_AUTH_METHOD=MUNGE" /etc/pbs.conf || echo "PBS_AUTH_METHOD=MUNGE" >> /etc/pbs.conf
+  grep -q 'PBS_SUPPORTED_AUTH_METHODS="munge"' /etc/pbs.conf || echo 'PBS_SUPPORTED_AUTH_METHODS="munge"' >> /etc/pbs.conf
 
   mkdir -p $(dirname ${mom_config}) 2>/dev/null
   grep '$clienthost' ${mom_config} 1>/dev/null 2>&1
